server:
  port: 8080

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://47.107.61.219:9411/
  sleuth:
    sampler:
      # 采样率 0~1，一般是 0.5，1 表示全部采集
      probability: 1
eureka:
  client:
    # 将自己注册到注册中心
    register-with-eureka: true
    # 从注册中心抓已注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
