server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lingouzi/springcloudconfigcenter
          #          uri: git@github.com:Lingouzi/springcloudconfigcenter.git
          search-paths:
            - springcloudconfigcenter
      label: master
  rabbitmq:
    host: 47.107.61.219
    port: 5672
    username: user
    password: JK4V4U6RDPXAHKU2



eureka:
  client:
    # 将当前项目注册到注册中心，默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true，单点无所谓，集群必须为 true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 主机名修改和 ip 地址展示
    instance-id: configCenter3344
    prefer-ip-address: true
# rabbitmq 相关配置
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
