server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh
          uri: http://localhost:8081
          predicates:
            - Path=/payment/get/**
        
        - id: payment-routh2
          uri: http://localhost:8081
          predicates:
            - Path=/payment/discoveryClient/**

eureka:
  client:
    # 将当前项目注册到注册中心，默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true，单点无所谓，集群必须为 true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 主机名修改和 ip 地址展示
    instance-id: gateway9527
    prefer-ip-address: true
    hostname: cloud-gateway-service
