server:
  port: 9001
spring:
  application:
    name: nacos-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.107:8848
management:
  endpoints:
    web:
      exposure:
        incloud: "*"
