server:
  port: 8084
spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      # zookeeper 注册中心
#      connect-string: 127.0.0.1:2181
      connect-string: 47.107.61.219:2181
