server:
  port: 8085
spring:
  application:
    name: nacos-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.107:8848
management:
  endpoints:
    web:
      exposure:
        incloud: "*"

service-url:
  nacos-payment-uri: http://nacos-provider-service
